name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - run: go mod tidy
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api-go ./cmd/main.go

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "api-go,migrations/"
          target: "/var/www/sespimma-api-go"
          overwrite: true

      - uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            source ~/.bashrc || true
            source ~/.profile || true
            cd /var/www/sespimma-api-go
            chmod +x api-go
            pm2 restart backend-golang
            pm2 save